services:
  mysql:
    image: mysql:8.4
    container_name: database-crud-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=cruddb
    ports: 
      - '3306:3306'
    networks: 
      - nlw-network

networks:
  nlw-network:
    driver: bridge
